### ISSUE TITLE
64-bit builds for Windows

### ISSUE THREAD

**Issue by Jan-E** [chung-leong/av#10]
I tried to compile the extension for Windows x64 (PHP 5.5). This was possible by adding a lib64 directory besides the lib directory and add Zeranoe's 64-bit libs over there. I used these libs:
http://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-20130424-git-aa96439-win64-dev.7z

Then I had to tweak the config.w32 a little bit:

```
PHP_CL = PATH_PROG('cl', null, 'PHP_CL');
if (!PHP_CL) {
    ERROR("MS C++ compiler is required");
}
X64 = probe_binary(PHP_CL, 64, null, 'PHP_CL');
if (X64) {
    ADD_FLAG("LIBS_AV", "ext\\av\\win32\\ffmpeg\\lib64\\avcodec.lib");
    ADD_FLAG("LIBS_AV", 'ext\\av\\win32\\ffmpeg\\lib64\\avformat.lib');
    ADD_FLAG("LIBS_AV", 'ext\\av\\win32\\ffmpeg\\lib64\\avutil.lib');
    ADD_FLAG("LIBS_AV", 'ext\\av\\win32\\ffmpeg\\lib64\\swscale.lib');
    ADD_FLAG("LIBS_AV", 'ext\\av\\win32\\ffmpeg\\lib64\\swresample.lib');
} else {
    ADD_FLAG("LIBS_AV", "ext\\av\\win32\\ffmpeg\\lib\\avcodec.lib");
    ADD_FLAG("LIBS_AV", 'ext\\av\\win32\\ffmpeg\\lib\\avformat.lib');
    ADD_FLAG("LIBS_AV", 'ext\\av\\win32\\ffmpeg\\lib\\avutil.lib');
    ADD_FLAG("LIBS_AV", 'ext\\av\\win32\\ffmpeg\\lib\\swscale.lib');
    ADD_FLAG("LIBS_AV", 'ext\\av\\win32\\ffmpeg\\lib\\swresample.lib');
}
```

**Comment by chung-leong** [comment]
I have never tried it. The win64 version of PHP is poorer in just about every possible way. On the other hand, it's a common enough set-up. I'll try to support it.

Sent from my Windows Phone

**Comment by Jan-E** [comment]
The Win64 version is stiil poorer at the moment. But the PHP guys (Anatol and Pierre) are doing all their best to catch up. Anyway, it works. For x64 PHP 5.3 and 5.4 Zeranoe's libs gave an error, so I had to recreate them. Dumpbin and Lib /def, you'll probably know the drill.

**Comment by chung-leong** [comment]
Honestly, I have not even tried. I have to thank you for making the attempt. It's just so busted at the moment.

Sent from my Windows Phone

**Comment by Jan-E** [comment]
OK, fine for the moment. If you want to support 64-bit, you know what to do. Could you at least make the change in config.w32, so I can 'git pull' any future changes?

I will close this issue for now. Thanks for the extension.

**Comment by chung-leong** [comment]
Okay. My last comment was from my phone. It looks like it is possible to make it work. I'll give it a shot.

**Comment by Jan-E** [comment]
I am sure it can be done. See the phpinfo.htm in
http://phpdev.toolsforresearch.com/php-5.5.10RC1-nts-Win32-VC11-x64.zip

**Comment by chung-leong** [comment]
Changes check into git. Tarballs updated.

**Comment by Jan-E** [comment]
As an afterthought: 64-bits FFMpeg is about 10% faster than 32-bits, so maybe the 64-bits extension will be faster after all. Thanks for the updates.

**Comment by chung-leong** [comment]
Maybe it'll be useful after all :-)

**Comment by Jan-E** [comment]
Maybe it is time to upgrade the Windows builds to FFmpeg 2.2.1:
http://ffmpeg.zeranoe.com/blog/?p=281#more-281

**Comment by chung-leong** [comment]
Doesn't sound like they've changed the API.

Date: Fri, 11 Apr 2014 05:42:44 -0700
